# Generated by Django 3.0.7 on 2021-03-13 21:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import mnemonic.news.search_indices


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('news', '0017_auto_20210115_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_crawled', models.BooleanField(default=False)),
                ('is_pushed_to_index', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            bases=(models.Model, mnemonic.news.search_indices.NewsIndexable),
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='NewsIndex',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
